name: Run test

on:
  push:
    tags:
      - 'run_tests'

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Config env
        run : |
          cp .env.local.phpstan.example .env
  test-job2:
    needs: [test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Add label to pull request
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels \
            -d '{"labels": ["ready_to_merge"]}'