name: Run tests and label on pull request

on:
  pull_request:
    types: [labeled]  # Запускается, когда метка добавляется к пулл-реквесту

jobs:
  check-label:
    runs-on: ubuntu-latest
    outputs:
      need_tests: ${{ steps.check_label.outputs.need_tests }}  # Установка выходных данных для следующего job
    steps:
      - name: Check for 'run_tests' label
        id: check_label
        run: |
          if [ "${{ github.event.label.name }}" == "run_tests" ]; then
            echo "need_tests=true" >> $GITHUB_ENV
            echo "::set-output name=need_tests::true"  # Устанавливаем выходные данные
          else
            echo "need_tests=false" >> $GITHUB_ENV
            echo "::set-output name=need_tests::false"  # Устанавливаем выходные данные
          fi

  run-tests:
    runs-on: ubuntu-latest
    needs: check-label  # Зависит от check-label
    if: needs.check-label.outputs.need_tests == 'true'  # Запустить только если метка 'help wanted' была найдена
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Config env
        run: |
          cp .env.local.phpstan.example .env

      - name: Run tests
        run: |
          npm test  # Запустите ваши тесты

  add-label:
    runs-on: ubuntu-latest
    needs: run-tests  # Зависит от run-tests
    if: success()  # Условие запуска, если предыдущий job прошел успешно
    steps:
      - name: Add label to pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Токен для аутентификации
        run: |
          # Получить номер пулл-реквеста из контекста
          PR_NUMBER=${{ github.event.pull_request.number }}

          # Использовать GitHub API для добавления метки
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels \
            -d '{"labels": ["ready_to_merge"]}'
